# Generated by Django 6.0.3 on 2026-03-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('benefits', models.TextField()),
                ('min_age', models.IntegerField(default=0)),
                ('max_age', models.IntegerField(default=100)),
                ('max_income', models.DecimalField(decimal_places=2, help_text='Maximum annual income to qualify', max_digits=10)),
                ('gender_target', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'All')], default='A', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
