# Generated by Django 6.0.3 on 2026-03-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='application_link',
            field=models.URLField(blank=True, default='', help_text='External portal URL for applications (optional)'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='target_occupation',
            field=models.CharField(blank=True, default='', help_text='Comma-separated occupations, or leave blank for all', max_length=300),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='max_income',
            field=models.DecimalField(decimal_places=2, help_text='Maximum annual income (₹) to qualify', max_digits=10),
        ),
    ]
