# Generated by Django 6.0.3 on 2026-03-12 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('meeting_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('agenda_pdf', models.FileField(blank=True, null=True, upload_to='agendas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ward')),
            ],
        ),
    ]
