# Generated by Django 6.0.3 on 2026-03-17 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='minutes_pdf',
            field=models.FileField(blank=True, null=True, upload_to='minutes/'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MeetingRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('attending', 'Attending'), ('not_attending', 'Not Attending'), ('tentative', 'Tentative')], default='attending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='governance.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_rsvps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('meeting', 'user')},
            },
        ),
    ]
