"""
Training data for complaint categorization model.
Contains sample complaints for each category.
"""

TRAINING_DATA = [
    # Water complaints
    ("Water supply not available in our area", "Water"),
    ("No water supply for 3 days", "Water"),
    ("Water pipe is leaking on the road", "Water"),
    ("Dirty water coming from tap", "Water"),
    ("Water tank is empty", "Water"),
    ("Water pressure is very low", "Water"),
    ("Drinking water quality is poor", "Water"),
    ("Water connection is broken", "Water"),
    ("Need new water connection", "Water"),
    ("Water motor not working", "Water"),
    ("Contaminated water supply", "Water"),
    ("Water shortage in our ward", "Water"),
    ("Broken water pipeline", "Water"),
    ("Water overflow from tank", "Water"),
    ("No drinking water facility", "Water"),
    ("Water pump needs repair", "Water"),
    ("Leaking water pipe near my house", "Water"),
    ("Water supply timing issue", "Water"),
    ("Bore well not working", "Water"),
    ("Water wastage due to leak", "Water"),
    
    # Electricity complaints
    ("Street light not working", "Street Light"),
    ("Power cut for long hours", "Electricity"),
    ("Electricity pole is damaged", "Electricity"),
    ("Electric wire hanging dangerously", "Electricity"),
    ("Transformer making noise", "Electricity"),
    ("No electricity since morning", "Electricity"),
    ("Frequent power cuts", "Electricity"),
    ("Electric meter not working", "Electricity"),
    ("Need new electricity connection", "Electricity"),
    ("Voltage fluctuation problem", "Electricity"),
    ("Electricity bill is wrong", "Electricity"),
    ("Power supply is irregular", "Electricity"),
    ("Electric pole fallen down", "Electricity"),
    ("Broken electric wire", "Electricity"),
    ("Transformer oil leaking", "Electricity"),
    ("Short circuit in street light", "Electricity"),
    ("Power outage in our area", "Electricity"),
    ("Electric cable damaged", "Electricity"),
    ("Electricity connection issue", "Electricity"),
    ("High voltage problem", "Electricity"),
    
    # Street Light complaints
    ("Street light not glowing", "Street Light"),
    ("All street lights are off", "Street Light"),
    ("Street lamp broken", "Street Light"),
    ("Need street light in our area", "Street Light"),
    ("Street light pole damaged", "Street Light"),
    ("Dark street at night no lights", "Street Light"),
    ("Street light bulb fused", "Street Light"),
    ("Street lighting not working", "Street Light"),
    ("Broken street lamp post", "Street Light"),
    ("Street light wire cut", "Street Light"),
    ("No street lights in our lane", "Street Light"),
    ("Street light switch not working", "Street Light"),
    ("LED street light not functioning", "Street Light"),
    ("Street light timing issue", "Street Light"),
    ("Dim street lights", "Street Light"),
    ("Street light cover broken", "Street Light"),
    ("Need more street lights", "Street Light"),
    ("Street light flickering", "Street Light"),
    ("Damaged street light fixture", "Street Light"),
    ("Street light maintenance required", "Street Light"),
    
    # Sanitation complaints
    ("Garbage not collected for days", "Sanitation"),
    ("Overflowing dustbin", "Sanitation"),
    ("Drainage blocked", "Sanitation"),
    ("Sewage water on road", "Sanitation"),
    ("Bad smell from garbage", "Sanitation"),
    ("Waste disposal not done", "Sanitation"),
    ("Drain cleaning required", "Sanitation"),
    ("Garbage bin is full", "Sanitation"),
    ("Sewage overflow problem", "Sanitation"),
    ("Dirty public toilet", "Sanitation"),
    ("Waste dumping on road", "Sanitation"),
    ("Manhole is open and dangerous", "Sanitation"),
    ("Stagnant water breeding mosquitoes", "Sanitation"),
    ("Garbage collection irregular", "Sanitation"),
    ("Blocked drainage system", "Sanitation"),
    ("Sewage pipe broken", "Sanitation"),
    ("Public toilet not cleaned", "Sanitation"),
    ("Waste segregation not done", "Sanitation"),
    ("Garbage truck not coming", "Sanitation"),
    ("Drain water entering house", "Sanitation"),
    
    # Roads complaints
    ("Road is full of potholes", "Roads"),
    ("Road needs repair", "Roads"),
    ("Damaged road causing accidents", "Roads"),
    ("Road construction incomplete", "Roads"),
    ("Broken road surface", "Roads"),
    ("Need road construction", "Roads"),
    ("Road is muddy and slippery", "Roads"),
    ("Potholes on main road", "Roads"),
    ("Road widening required", "Roads"),
    ("Uneven road surface", "Roads"),
    ("Road tar work needed", "Roads"),
    ("Cracked road pavement", "Roads"),
    ("Road flooding during rain", "Roads"),
    ("Speed breaker damaged", "Roads"),
    ("Road side drain broken", "Roads"),
    ("Kutcha road needs paving", "Roads"),
    ("Road maintenance required", "Roads"),
    ("Damaged road divider", "Roads"),
    ("Road marking faded", "Roads"),
    ("Narrow road needs expansion", "Roads"),
    
    # Other complaints
    ("Stray dogs menace in area", "Other"),
    ("Illegal construction happening", "Other"),
    ("Noise pollution from factory", "Other"),
    ("Tree branches need trimming", "Other"),
    ("Park maintenance required", "Other"),
    ("Encroachment on public land", "Other"),
    ("Bus stop shelter damaged", "Other"),
    ("Public property vandalized", "Other"),
    ("Illegal parking problem", "Other"),
    ("Traffic signal not working", "Other"),
    ("Footpath broken", "Other"),
    ("Boundary wall collapsed", "Other"),
    ("Community hall needs repair", "Other"),
    ("Playground maintenance needed", "Other"),
    ("Illegal shop on footpath", "Other"),
    ("Public bench broken", "Other"),
    ("Signboard fallen down", "Other"),
    ("Cattle roaming freely", "Other"),
    ("Anti-social activities", "Other"),
    ("Public nuisance", "Other"),
]

# Category labels
CATEGORIES = ["Water", "Electricity", "Street Light", "Sanitation", "Roads", "Other"]
