# Generated by Django 6.0.3 on 2026-03-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='citizen_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5 stars', null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution_image',
            field=models.ImageField(blank=True, null=True, upload_to='resolutions/'),
        ),
    ]
