# Generated by Django 6.0.3 on 2026-03-17 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaintstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='parent_complaint',
            field=models.ForeignKey(blank=True, help_text='If this is a duplicate, link to the master complaint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_duplicates', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='potential_duplicate_of',
            field=models.ForeignKey(blank=True, help_text='AI-flagged candidate for merging', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potential_matches', to='complaints.complaint'),
        ),
    ]
