# Generated by Django 6.0.3 on 2026-03-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_parent_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ai_analysis_reason',
            field=models.TextField(blank=True, help_text='Reason why AI prioritized or flagged this issue', null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('urgent_review', 'Urgent Review'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaintstatushistory',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('urgent_review', 'Urgent Review'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
