# Generated by Django 6.0.3 on 2026-03-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_complaint_ai_analysis_reason_alter_complaint_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolution_report',
            field=models.TextField(blank=True, help_text='Work completion summary by the field worker', null=True),
        ),
    ]
