# Generated by Django 6.0.3 on 2026-03-25 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaint_resolution_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5')),
                ('feedback_text', models.TextField(help_text="Citizen's feedback on resolution")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='complaints.complaint')),
            ],
            options={
                'verbose_name': 'Complaint Feedback',
                'verbose_name_plural': 'Complaint Feedbacks',
            },
        ),
    ]
